const envConfig = {
  SERVER_DOMAIN: process.env.BACKEND_DOMAIN || "",
  SERVER_PORT: process.env.BACKEND_PORT || 3000,

  FRONTEND_PROTOCOL: process.env.FRONTEND_PROTOCOL,
  FRONTEND_DOMAIN: process.env.FRONTEND_DOMAIN,
  FRONTEND_PORT: process.env.FRONTEND_PORT,

  DATABASE_URL: process.env.DATABASE_URL,

  JWT_ACCESS_SECRET: process.env.JWT_ACCESS_SECRET || "",
  JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET || "",
  JWT_ACCESS_EXPIRES_IN: process.env.JWT_ACCESS_EXPIRES_IN,
  JWT_REFRESH_EXPIRES_IN: process.env.JWT_REFRESH_EXPIRES_IN
};

export default envConfig;
