#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged

# Check for changes in @playnest/core
CHANGED=$(git diff --name-only HEAD~1 HEAD packages/core/ | wc -l)

if [ "$CHANGED" -gt 0 ]; then
  echo "🚀 Updating package version..."
  cd packages/core || exit

  CURRENT_VERSION=$(node -p "require('./package.json').version")
  NEW_VERSION=$(npm version patch --no-git-tag-version)

  git stash push --keep-index --quiet
  git add package.json
  git commit -m "chore(@playnest/core): version patch [v$CURRENT_VERSION → $NEW_VERSION]" --no-verify
  git stash pop --quiet

  echo "🔄 @playnest/core updated version: v$CURRENT_VERSION → $NEW_VERSION"
fi

# git commit -m "msg" --publish
