#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Check for changes in @playnest/configs
CHANGED_CONFIGS=$(git diff --name-only "origin/$(git rev-parse --abbrev-ref HEAD)" HEAD packages/configs/ | wc -l)
if [ "$CHANGED_CONFIGS" -gt 0 ]; then
  echo "❗Changes detected in @playnest/configs. Publishing is required"
  echo 'Run "pnpm push-publish" to push changes and publish packages'
  exit 1
fi
